### ISSUE TITLE
fragment==null？

### ISSUE THREAD

**Issue by lizhangqu** [openproject/AndroidDigest#4]
case R.id.tab_home_btn:
                   // if (homeFragment == null) {
                    //    homeFragment = fragmentManager.findFragmentByTag(TAG_HOME);
                    //}
                    changeFrament(homeFragment);
                    break;
                case R.id.tab_blog_btn:
                   // if (blogFragment == null) {
                    //    blogFragment = fragmentManager.findFragmentByTag(TAG_BLOG);
                   // }
                    changeFrament(blogFragment);
                    break;
                case R.id.tab_tool_btn:
                 //   if (toolFragment == null) {
                  //      toolFragment = fragmentManager.findFragmentByTag(TAG_TOOL);
                  //  }
                    changeFrament(toolFragment);
                    break;
 fragment已经初始化了，判断==NUll是否还有意义？

**Comment by openproject** [comment]
这是碰到了一个random问题：fragment在切换到后台再切换到前台的时候，changeFragment没效果，我怀疑是空了，所以加了判断，实际上后来还是复现了这个bug，看来还需要修改。难的是重现。

**Comment by lizhangqu** [comment]
你的tag只有Home设置了，其他fragment的tag都没设置，都是是默认的，fragmentManager.findFragmentByTag(TAG_TOOL);这样获得的难道不是null？

**Comment by openproject** [comment]
是的，这个地方写的太有问题了

**Comment by openproject** [comment]
有没有兴趣来优化一下这个地方？

**Comment by lizhangqu** [comment]
fragment先别初始化，显示时通过findFragmentByTag方法来判断是否为null，为null时初始化fragment并add（记得加tag），否则直接show，试试看这种思路

**Comment by openproject** [comment]
试试

**Comment by openproject** [comment]
上面说的问题，可以重现：打开开发者模式 - 不保留活动 - 开启。再把应用打开， 按Home键，再进入应用，就发现下面的tab点了没反应了。

**Comment by lizhangqu** [comment]
MainActivity实现一个空的onSaveInstanceState方法可解决该bug
    @Override
    protected void onSaveInstanceState(Bundle outState) {
       // super.onSaveInstanceState(outState);
    }

**Comment by lizhangqu** [comment]
MainActivity实现一个空的onSaveInstanceState方法可解决该bug，注释掉调用父类的语句
@Override
protected void onSaveInstanceState(Bundle outState) {
// super.onSaveInstanceState(outState);
}

**Comment by openproject** [comment]
Perfect! 解决问题。有微博，qq，或者微信否，有问题以后可以讨论讨论 也欢迎加群451634330

**Comment by lizhangqu** [comment]
已经在群里了，这样解决毕竟不是最完美的，这个问题的本质应该出在生命周期上，可以从生命周期上入手寻找更好的解决方法

**Comment by openproject** [comment]
看来有空要研究一下onSaveInstanceState方法了。
这个bug就先关掉了
